# Generated by Django 2.0.5 on 2018-06-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0004_manager_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('accumulator', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='manager.Restaurant')),
            ],
        ),
    ]
