# Generated by Django 2.0.5 on 2018-06-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_id', models.CharField(default='', max_length=70)),
                ('accumulator', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='manager.Restaurant')),
            ],
        ),
    ]
