# Generated by Django 2.0.5 on 2018-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
