# Generated by Django 2.0.5 on 2018-05-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
                ('dishes', models.ManyToManyField(to='manager.Dish')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='manager.Seat')),
            ],
        ),
    ]
