# Generated by Django 2.0.5 on 2018-06-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='noUsername', max_length=30),
        ),
    ]
