# Generated by Django 2.0.5 on 2018-11-19 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('stripe_id', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.Cafe')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('time_to_do', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('cafe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cafe.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='ItemObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_object', to='cafe.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_object', to='cafe.CustomerOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=False)),
                ('cafe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cafe.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('is_owner', models.BooleanField(default=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='cafe.Cafe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='size', to='cafe.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('cafe', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to='cafe.Cafe')),
            ],
        ),
        migrations.AddField(
            model_name='itemobject',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_object', to='cafe.Size'),
        ),
        migrations.AddField(
            model_name='item',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cafe.Terminal'),
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cafe.Menu'),
        ),
    ]
