# Generated by Django 2.0.5 on 2018-11-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
