# Generated by Django 2.0.5 on 2018-11-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20181123_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemobject',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_object', to='cafe.CustomerOrder'),
        ),
    ]
