# Generated by Django 2.0.5 on 2018-11-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20181117_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='size', to='cafe.Item')),
            ],
        ),
    ]
