# Generated by Django 2.0.5 on 2018-11-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.Cafe')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.Customer')),
                ('items', models.ManyToManyField(to='cafe.Item')),
            ],
        ),
    ]
