# Generated by Django 2.0.5 on 2018-11-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cafe.Terminal'),
        ),
    ]
