# Generated by Django 2.0.5 on 2018-11-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_item_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
