# Generated by Django 2.0.5 on 2018-11-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_customerorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cafe.Cafe'),
        ),
    ]
