# Generated by Django 2.0.5 on 2018-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='time_to_do',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seat',
            name='payed',
            field=models.BooleanField(default=True),
        ),
    ]
