# Generated by Django 2.0.5 on 2018-10-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='stripe_id',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
