# Generated by Django 2.0.5 on 2018-06-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180530_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
