# Generated by Django 2.0.5 on 2018-06-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_seat_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
